version: "3.9"

services:
  container_database_name:
    image: postgres
    container_name: container_database_name
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=database_name
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: container_app_name
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - container_database_name
    depends_on:
      - container_database_name


volumes:
  pgdata:
    driver: local
